apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - ingress.yaml

namespace: auraweb-dev

commonLabels:
  environment: development

images:
  - name: frontend
    newName: your-registry.com/auraweb/frontend
    newTag: latest
  - name: admin
    newName: your-registry.com/auraweb/admin
    newTag: latest
  - name: gateway
    newName: your-registry.com/auraweb/gateway
    newTag: latest
  - name: catalog
    newName: your-registry.com/auraweb/catalog
    newTag: latest
  - name: inventory
    newName: your-registry.com/auraweb/inventory
    newTag: latest
  - name: shopping
    newName: your-registry.com/auraweb/shopping
    newTag: latest
  - name: order-payment
    newName: your-registry.com/auraweb/order-payment
    newTag: latest
  - name: fulfillment
    newName: your-registry.com/auraweb/fulfillment
    newTag: latest
  - name: user-auth
    newName: your-registry.com/auraweb/user-auth
    newTag: latest
  - name: platform
    newName: your-registry.com/auraweb/platform
    newTag: latest

patches:
  - target:
      kind: Deployment
    patch: |-
      - op: add
        path: /spec/template/spec/containers/0/env/-
        value:
          name: LOG_LEVEL
          value: debug
