apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- ingress.yaml
namespace: auraweb-dev
labels:
- includeSelectors: true
  includeTemplates: true
  pairs:
    environment: development
images:
- name: frontend
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-frontend
  newTag: build-12-c8ae922
- name: admin
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-admin
  newTag: build-12-c8ae922
- name: gateway
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-gateway
  newTag: build-12-c8ae922
- name: catalog
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-catalog
  newTag: build-12-c8ae922
- name: inventory
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-inventory
  newTag: build-12-c8ae922
- name: shopping
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-shopping
  newTag: build-12-c8ae922
- name: order-payment
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-order-payment
  newTag: build-12-c8ae922
- name: fulfillment
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-fulfillment
  newTag: build-12-c8ae922
- name: user-auth
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-user-auth
  newTag: build-12-c8ae922
- name: platform
  newName: 429104603739.dkr.ecr.us-east-1.amazonaws.com/auraweb-platform
  newTag: build-12-c8ae922
